use crate::providers::http_client;
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
struct UserResp {
    login: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Repo {
    pub name: String,
    pub full_name: String,
    pub private: bool,
    pub clone_url: String,
    pub html_url: String,
    pub default_branch: String,
}

#[derive(Deserialize)]
struct RepoApi {
    name: String,
    full_name: String,
    private: bool,
    clone_url: String,
    html_url: String,
    default_branch: Option<String>,
}

impl From<RepoApi> for Repo {
    fn from(r: RepoApi) -> Self {
        Self {
            name: r.name,
            full_name: r.full_name,
            private: r.private,
            clone_url: r.clone_url,
            html_url: r.html_url,
            default_branch: r.default_branch.unwrap_or_else(|| "main".to_string()),
        }
    }
}

#[derive(Serialize)]
struct CreateRepoReq<'a> {
    name: &'a str,
    private: bool,
    auto_init: bool,
    description: &'a str,
}

pub struct GitHub {
    token: String,
}

impl GitHub {
    pub fn new(token: String) -> Self {
        Self { token }
    }

    async fn req(&self, method: reqwest::Method, path: &str) -> reqwest::RequestBuilder {
        http_client()
            .request(method, format!("https://api.github.com{}", path))
            .header("Accept", "application/vnd.github+json")
            .header("X-GitHub-Api-Version", "2022-11-28")
            .bearer_auth(&self.token)
    }

    pub async fn whoami(&self) -> anyhow::Result<String> {
        let resp = self.req(reqwest::Method::GET, "/user").await.send().await?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            anyhow::bail!("GitHub /user {}: {}", status, body);
        }
        let u: UserResp = resp.json().await?;
        Ok(u.login)
    }

    pub async fn list_repos(&self) -> anyhow::Result<Vec<Repo>> {
        let resp = self
            .req(
                reqwest::Method::GET,
                "/user/repos?per_page=100&sort=updated&affiliation=owner",
            )
            .await
            .send()
            .await?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            anyhow::bail!("GitHub list repos {}: {}", status, body);
        }
        let list: Vec<RepoApi> = resp.json().await?;
        Ok(list.into_iter().map(Into::into).collect())
    }

    pub async fn create_repo(&self, name: &str, private: bool) -> anyhow::Result<Repo> {
        let body = CreateRepoReq {
            name,
            private,
            auto_init: true,
            description: "Generated by ImgPlayGround",
        };
        let resp = self
            .req(reqwest::Method::POST, "/user/repos")
            .await
            .json(&body)
            .send()
            .await?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            anyhow::bail!("GitHub create repo {}: {}", status, body);
        }
        let r: RepoApi = resp.json().await?;
        Ok(r.into())
    }
}

/// Build a push URL that embeds the PAT. Never stored — only passed to a
/// single `git push` invocation. Works with GitHub's "x-access-token" scheme.
pub fn tokenized_push_url(clone_url: &str, token: &str) -> String {
    // clone_url looks like "https://github.com/owner/repo.git"
    if let Some(rest) = clone_url.strip_prefix("https://") {
        format!("https://x-access-token:{}@{}", token, rest)
    } else {
        clone_url.to_string()
    }
}
